version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: 'rb-shop-symfony'
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
